# Generated by Django 5.0.7 on 2024-07-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogDetail',
            fields=[
                ('Blog_id', models.AutoField(primary_key=True, serialize=False)),
                ('Blog_Title', models.CharField(max_length=50)),
                ('Blog_Desc', models.CharField(max_length=400)),
                ('Blog_Date', models.DateTimeField()),
            ],
            options={
                'db_table': 'BlogTable',
            },
        ),
    ]
